services:
  laodog-bonus-claim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laodog-bonus-claim
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./data:/var/www/html/data
